<?php
$email = $_SESSION['email'] ?? '';
if (isset($_SESSION['confirm']) && $_SESSION['confirm'] === 100000) {
  $_SESSION['confirm'] = 0;
  $_SESSION['error'] = '';
}

/*TWIG START*/
use Twig\Environment;
use Twig\Error\LoaderError;
use Twig\Error\RuntimeError;
use Twig\Error\SyntaxError;
use Twig\Loader\FilesystemLoader;
$loader = new FilesystemLoader(__DIR__ );
$twig = new Environment($loader);
$twig->addGlobal('vars',
  [
    'pathToSite' => $pathToSite,
    'email' => $email,
    'sessionError' => $_SESSION['errors'] ?? ''
  ]);
try {
  echo $twig->render('login-twig.twig');
} catch (LoaderError|RuntimeError|SyntaxError $e) {}
/*TWIG END*/

$_SESSION['email'] = '';

