<?php
$user = json_decode($_SESSION['user'], true);
$name = $user['name'];
$email = $user['email'];
$regdate = date('d-m-Y', $user['regdate']);
$role = $user['role'] ? 'Admin' : 'User';
$roleSwitch = $user['role'] ? 'User' : 'Admin';
$lastPosts = json_decode($_SESSION['lastposts'], true);
const FORM_CLASS = 'form';
?>
<main class="main">
  <div class="user">
    <label>
      <h2>Hi, <?=$name?></h2>
    </label>
    <?php if ($user['role']):?>
    <label>
      <div>Your id: <?=$_SESSION['id']?></div>
    </label>
    <label>
      <div>Your email: <?=$email?></div>
    </label>
    <label>
      <div>Your are here since: <?=$regdate?></div>
    </label>
    <?php endif;?>
    <label>
      <div>Your role is: <?=$role?></div>
    </label>
    <label>
      <form class="<?=FORM_CLASS?>"
          id="change_role"
          name="change_role"
          method="POST"
          action="<?=$pathToSite?>user/changerole"
          enctype="multipart/form-data">
        <input name="changerole" type="submit" value="Change role to <?=$roleSwitch?>">
    </form>
    </label>
    <label>
      <form class="<?=FORM_CLASS?>"
        id="post_to_blog"
        name="post_to_blog"
        method="POST"
        action="<?=$pathToSite?>blog/post"
        enctype="multipart/form-data"
      >
         <h3>Post to blog</h3>
        <textarea name="posttext"></textarea>
        <label><span>Add a picture</span><input type="file" id="images" name="images" accept="image/*"></label>
        <input name="addpost" id="addpost" type="submit" value="Add post">
      </form>
    </label>
    <?php if ($user['role']):?>
      <form class="<?=FORM_CLASS?>"
        name="postapi"
        method="POST"
        action="<?=$pathToSite?>blog/postapi"
        enctype="multipart/form-data"
      >
        <h3>Enter user id to get his/her 20 last posts</h3>
        <label>
            <input name="user_id" type="number">
        </label>
        <input name="submit" type="submit" value="TEST API">
        <label>
         <small>API url: /blog/postapi POST only</small>
        </label>
      </form>
    <?php endif;?>
    <label>
      <div class='errors'><?= $_SESSION['errors'] ?></div>
    </label>
  </div>
  <div class="blog">
    <?php if ($user['role']):?>
        <form class="<?=FORM_CLASS?> remove-post"
              name="remove_post"
              method="POST"
              action="<?=$pathToSite?>blog/removepost"
              enctype="multipart/form-data"
        >
    <?php endif;?>
    <?php foreach($lastPosts as $post): ?>
      <div class="blog-post">
        <div class="post-author">
          Name: <?=$post['userName']?>
          ID: <?=$post['userID']?>
        </div>
        <div class="post-date">
          <?=date('d-m-Y', $post['date'])?>
        </div>
        <div class="post-content">
          <?php if ($post['image']):?>
            <img src="<?=$post['image']?>"/>
          <?php endif;?>
          <?=$post['text']?>
        </div>
          <?php if ($user['role'] && $post['userID'] === $_SESSION['id']):?>
            <div class='post-remove'>
              <input name="submit<?=$post['id']?>>" type='submit' value='Remove post'>
            </div>
          <?php endif;?>
      </div>
    <?php endforeach; ?>
    <?php if ($user['role']):?>
        </form>
    <?php endif;?>
  </div>
  <h4><a class="signout" href="<?=$pathToSite?>user/signout">Sign out</a></h4>
</main>
